version: "3.3"

services:
  dsbpa:
    image: meetveracity/coding-challenge-app
    build: 
      context: .
    environment:
      - RAILS_ENV=test
      - DATABASE_USER=dsbpa
      - DATABASE_PASSWORD=dsbpa
      - DATABASE_HOST=postgres
      - DATABASE_SCHEMA=${DATABASE_SCHEMA:-dsbpa_test}
      - DATABASE_PORT=5432
    ports:
      - "8080:8080"

  db-init:
    image: meetveracity/coding-challenge-db-init
    build: 
      context: .
      dockerfile: Dockerfile.db-init
    environment:
      - RAILS_ENV=test
      - DATABASE_USER=dsbpa
      - DATABASE_PASSWORD=dsbpa
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=${DATABASE_SCHEMA:-dsbpa_test}
  
  postgres:
    image: library/postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=dsbpa
      - POSTGRES_USER=dsbpa
      - POSTGRES_DB=${DATABASE_SCHEMA:-dsbpa_test}
    ports:
      - "5432:5432"